In [12]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.linalg import expm

In [13]:
# operators
sigma = np.matrix([[0, 0], [1, 0]])
numPts = 1000
numdt = 1000
Tp = 1.0
dt = Tp/numdt
gamma = 1.0
Omega_0 = np.linspace(0, 10, numPts)

In [18]:
ground = np.matrix([[0], [1]])
P0gResult = []
for ii in range(numPts):
    H_eff = -1.0j*gamma/2*np.dot(np.conjugate(sigma),sigma) + Omega_0[ii]*(sigma + np.conjugate(sigma))
    U_eff = np.matrix([[1.0, 1.0], [1.0, 1.0]])
    for ndt in range(numdt):
        U_effTemp = expm(-1.0j*dt*H_eff)
        U_eff = np.dot(U_effTemp, U_eff)
    P0g = np.dot(ground.T, np.dot(U_eff, ground))
    P0gResult.append(P0g)

In [32]:
P0gResult

[matrix([[1.+0.j]]),
 matrix([[1.-0.02002002j]]),
 matrix([[1.-0.04004004j]]),
 matrix([[1.-0.06006006j]]),
 matrix([[1.-0.08008008j]]),
 matrix([[1.-0.1001001j]]),
 matrix([[1.-0.12012012j]]),
 matrix([[1.-0.14014014j]]),
 matrix([[1.-0.16016016j]]),
 matrix([[1.-0.18018018j]]),
 matrix([[1.-0.2002002j]]),
 matrix([[1.-0.22022022j]]),
 matrix([[1.-0.24024024j]]),
 matrix([[1.-0.26026026j]]),
 matrix([[1.-0.28028028j]]),
 matrix([[1.-0.3003003j]]),
 matrix([[1.-0.32032032j]]),
 matrix([[1.-0.34034034j]]),
 matrix([[1.-0.36036036j]]),
 matrix([[1.-0.38038038j]]),
 matrix([[1.-0.4004004j]]),
 matrix([[1.-0.42042042j]]),
 matrix([[1.-0.44044044j]]),
 matrix([[1.-0.46046046j]]),
 matrix([[1.-0.48048048j]]),
 matrix([[1.-0.5005005j]]),
 matrix([[1.-0.52052052j]]),
 matrix([[1.-0.54054054j]]),
 matrix([[1.-0.56056056j]]),
 matrix([[1.-0.58058058j]]),
 matrix([[1.-0.6006006j]]),
 matrix([[1.-0.62062062j]]),
 matrix([[1.-0.64064064j]]),
 matrix([[1.-0.66066066j]]),
 matrix([[1.-0.68068068j]]),

In [26]:
P0gResult[0][0][0].dtype

dtype('complex128')